### ISSUE TITLE
Can you provide more metric code?

### ISSUE THREAD

**Issue by shydyl** [qym7/CBDM-pytorch#1]
Thanks for you great work!
Can you provide the other metric (Recall, $F_{\beta}$) code?

**Comment by akp223** [comment]
Could you please provide the code for CelebA dataset also. for reference. Thank you

**Comment by GuangtaoLyu** [comment]
+1

**Comment by yanliang3612** [comment]
+1

**Comment by yanliang3612** [comment]
+1

**Comment by qym7** [comment]
Hi, thanks for your feedback.
The codes for those metrics have been added.

**Comment by yanliang3612** [comment]
<img width="423" alt="image" src="https://github.com/qym7/CBDM-pytorch/assets/100582544/02bcfb4b-d9cb-4a3c-9f78-5927ff3820cd">
1
