### ISSUE TITLE
Some issues related to hyperparameters in CBDM

### ISSUE THREAD

**Issue by backwards123** [qym7/CBDM-pytorch#5]
Thank you very much for your work! But recently, when reproducing, I found that except for the normal indicators of CIFAR100lt, all other datasets are not quite normal. Therefore, I would like to know the hyperparameter settings of other datasets, such as -- total_steps in training and -- sample_method -- omega in eval, on CIFAR100 and CIFAR10，thanks！

**Comment by qym7** [comment]
Hi,

Thank you for your interest.
One possible reason is that for the fact that CIFAR100 and CIFAR10 are larger than its longtail version, they require longer training iterations.
Please refer to the original repo (https://github.com/w86763777/pytorch-ddpm) for the corresponding setting, where the total_steps is set to 800000.

Best,

**Comment by backwards123** [comment]
Thank you for your reply. I will try again. thanks!
