### ISSUE TITLE
How to obtain the CBDM approach cpkt file

### ISSUE THREAD

**Issue by Gbone3176** [qym7/CBDM-pytorch#6]
Such an excellent work！how can i obtain the   ‘’--finetune --finetuned_logdir cifar100lt_cbdm_finetune --ckpt_step 200000‘’  file to train my own model？thanks a lot!

**Comment by qym7** [comment]
Thank you for your interest.
We regret that the ckpt are no longer available now. 😞

**Comment by Gbone3176** [comment]
I understand，thanks for replying~
